### ISSUE TITLE
client 400 error on "Create card" gives JsonParseException: "Unexpected character ('i' (code 105)): " for any client errors

### ISSUE THREAD

**Issue by alexeyOnGitHub** [taskadapter/trello-java-wrapper#25]
> com.fasterxml.jackson.core.JsonParseException: Unexpected character ('i' (code 105)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
>  at [Source: org.apache.http.conn.EofSensorInputStream@5e8a459; line: 1, column: 2]

this is thrown instead of a user-friendly error when creating a card with some fields filled out incorrectly 

the actual error is:

> invalid value for idList

found deep inside the parsing code using this hack in debugger:

`new java.util.Scanner(((org.apache.http.conn.BasicManagedEntity) httpEntity).wrappedEntity.getContent()).useDelimiter("\\A").next()`
)

**Comment by alexeyOnGitHub** [comment]
if I debug parsing code, I eventually find out the actual error:

> invalid value for idList


with this hack in debugger:

`new java.util.Scanner(((org.apache.http.conn.BasicManagedEntity) httpEntity).wrappedEntity.getContent()).useDelimiter("\\A").next()`

**Comment by alexeyOnGitHub** [comment]
same behavior on any other client errors, actually.

**Comment by alexeyOnGitHub** [comment]
FYI - fixed in this fork - https://github.com/taskadapter/trello-java-wrapper

given that last commits in this original repo are from 2016, we (TaskAdapter team) will be maintaining our own fork of this library. everyone is welcome to use it.

**Comment by julienvey** [comment]
Hi, @alexeyOnGitHub

We no longer have time (and motivation) to maintain this repo, but if you want, we can transfer its ownership to you, this way, people looking for this repo would be transfered directly to yours.

Let me know and I can do it as soon as you want
Julien

**Comment by julienvey** [comment]
@alexeyOnGitHub doc is here https://help.github.com/articles/about-repository-transfers/

**Comment by alexeyOnGitHub** [comment]
Hi Julien! alright, let's do this. I renamed my fork to avoid name conflict.

**Comment by julienvey** [comment]
Hi @alexeyOnGitHub.

I can't transfer the repo to `taskadapter` since your fork (even if the name was changed) is in the same network as this original repo. The cleanest way to go is to contact github support to "unlink" the fork from its parent (the doc mentionning it is [here](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork))

> To detach the fork and turn it into a standalone repository on GitHub, contact [GitHub Support](https://github.com/contact). If the fork has forks of its own, let support know if the forks should move with your repository into a new network or remain in the current network. For more information, see "[About forks.](https://help.github.com/articles/about-forks/)"

I've already done this once for another repo, and it wasn't so long

The other way is to delete and recreate the repo :(

**Comment by alexeyOnGitHub** [comment]
I moved that fork to another account. now you should be good to go

**Comment by julienvey** [comment]
I can't transfer it on taskadapter because "I don't have permissions to create repo"

So I can transfer it to your personnal account and you can do the transfer to taskadapter yourself I guess. But you will need to move your personal fork :(

Sorry about that :( I thought it would just send you some kind of "transfer request". I also had to transfer it to my personnal account because transfer between organizations does not seem to be permitted at this time

We'll get there !

**Comment by alexeyOnGitHub** [comment]
Alright, the original issue reported in this ticket is now fixed in "master" branch. Released in version 0.4. I will deploy it to Maven Central soon.
